_wandb:
    value:
        cli_version: 0.21.3
        code_path: code/hw0/handout/txt_classifier.py
        e:
            4ad8jsbtrqt8j2jm256g7d4i6eddj39r:
                args:
                    - --batch_size
                    - "1"
                    - --max_len
                    - "-1"
                    - --use_wandb
                codePath: hw0/handout/txt_classifier.py
                codePathLocal: txt_classifier.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "75125227520"
                        used: "16404586496"
                email: shrinivasr@iisc.ac.in
                executable: /zfsauton2/home/shrinivr/miniconda3/envs/py312/bin/python
                git:
                    commit: 6bd6f3939f530e3044c7bb1741c7c2f9e58d59da
                    remote: https://github.com/stablegradients/10-623.git
                gpu: NVIDIA RTX A6000
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-69fcfce7-32ac-8aff-92c3-63ae5ee364c4
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-9a648eaf-ecff-38bf-dd6e-655d9ec03932
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-8f9f7fbb-31dd-3c73-bdfc-417cae0b642a
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-00a8bc8e-fac0-b46d-cd7b-32117caac26e
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-64444b52-3375-b1d3-c865-df5135146f5a
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-a4b7f905-eb96-3305-d6a9-b629c58b6618
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-9636ab1f-b714-8ee2-982a-0a8908502fd1
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-846af4c2-183b-ba07-8eaa-d3e44595c570
                host: gpu30.int.autonlab.org
                memory:
                    total: "506526789632"
                os: Linux-5.14.0-284.11.1.el9_2.x86_64-x86_64-with-glibc2.34
                program: /zfsauton2/home/shrinivr/10-623/hw0/handout/txt_classifier.py
                python: CPython 3.12.11
                root: /zfsauton2/home/shrinivr/10-623/hw0/handout
                startedAt: "2025-09-02T04:46:26.202803Z"
                writerId: 4ad8jsbtrqt8j2jm256g7d4i6eddj39r
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.12.11
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
batch_size:
    value: 1
embed_dim:
    value: 64
epochs:
    value: 5
lr:
    value: 5
max_len:
    value: -1
model:
    value: simple
optimizer:
    value: sgd
